acceptanc tests

diff --git a/.one-pipeline.yaml b/.one-pipeline.yaml
--- a/.one-pipeline.yaml
+++ b/.one-pipeline.yaml
@@ -42,6 +42,56 @@ setup:
       echo "git push --prune https://$GHE_TOKEN@$WHITESOURCE_GHE_REPO $BRANCH_REFSPEC +refs/tags/*:refs/tags/*"
       git push --prune https://$GHE_TOKEN@$WHITESOURCE_GHE_REPO $BRANCH_REFSPEC +refs/tags/*:refs/tags/*
     fi
+
+    timestamp=$(date +%s)
+    echo $timestamp
+    wlo_demand_id="wlo_$timestamp"
+    set_env WLO_DEMAND_ID "$wlo_demand_id"
+    echo "wlo_demand_id=$wlo_demand_id"
+    
+    git clone https://$(get_env git-token)@github.ibm.com/elastic-build-cloud/ebc-gateway-http.git
+    cd ebc-gateway-http
+
+    export intranetId_USR=$(get_env ebc_id)
+    export intranetId_PSW=$(get_env ebc_pw)
+    export demandId=$wlo_demand_id
+
+    PRE_RELEASE=$(get_env pre-release)
+    PRE_RELEASE="$(echo "$PRE_RELEASE" | tr '[:upper:]' '[:lower:]')"
+    if [[ ! -z "$PRE_RELEASE" && "$PRE_RELEASE" != "false" && "$PRE_RELEASE" != "no"  ]]; then
+      rhcos_level=$(get_env pre-release-rhcos-url)
+      ocp_level=$(get_env pre-release-ocp-url)
+      echo "this is a pre-release OCP cluster build"
+      echo "ocp level: $ocp_level"
+      echo "core os level: $rhcos_level"
+      export ebc_plan=svl-onepipeline-ocpplus_x_custom.yml
+      export ebc_fyre_kernel_url=${rhcos_level}/rhcos-live-kernel-x86_64
+      export ebc_fyre_initramfs_url=${rhcos_level}/rhcos-live-initramfs.x86_64.img
+      export ebc_fyre_metal_url=${rhcos_level}/rhcos-metal.x86_64.raw.gz
+      export ebc_fyre_rootfs_url=${rhcos_level}/rhcos-live-rootfs.x86_64.img
+      export ebc_fyre_install_url=${ocp_level}/openshift-install-linux.tar.gz
+      export ebc_fyre_client_url=${ocp_level}/openshift-client-linux.tar.gz
+    else
+      export ebc_plan=svl-onepipeline-ocpplus_x.yml
+      export ebc_ocp_version=$(get_env ocp_version)
+    fi
+    # prod or dev, start out with dev
+    export ebcEnvironment=dev
+    # priority is 30 to start, prod priority may be 100
+    export ebc_priority=30
+    export ebc_autoCompleteAfterXHours=$(get_env ebc_autocomplete_hours "6")
+    # gather pipeline URL and place in following env var
+    reason="https://cloud.ibm.com/devops/pipelines/tekton/${PIPELINE_ID}/runs/${PIPELINE_RUN_ID}"
+    export ebc_reasonForEnvironment=$reason
+    
+    ./ebc_demand.sh
+    rc=$?
+    if [[ "$rc" == 0 ]]; then
+      echo "cluster requested"
+    else
+      echo "Outage impacting demand of cluster, try again later"
+      exit 1
+    fi
   
 test:
   dind: true
@@ -218,30 +268,143 @@ acceptance-test:
     PERIODIC_SCAN="$(echo "$PERIODIC_SCAN" | tr '[:upper:]' '[:lower:]')"
 
     if [[ ! -z "$PERIODIC_SCAN" && "$PERIODIC_SCAN" != "false" && "$PERIODIC_SCAN" != "no"  ]]; then
-      echo "Skipping e2e-tests. This is a periodic run that is only meant to produce CVE information."
+      echo "Skipping acceptance-test. This is a periodic run that is only meant to produce CVE information."
       exit 0
     fi
 
-    GO_VERSION=$(get_env go-version)
-    export SKIP_KIND_E2E_TEST=$(get_env SKIP_KIND_E2E_TEST)
-    if [[ $SKIP_KIND_E2E_TEST != "true" ]]; then
-      # Download and configure golang
-      wget --header "Accept: application/octet-stream"  "https://golang.org/dl/go$GO_VERSION.linux-amd64.tar.gz" 
-      rm -rf /usr/local/go && tar -C /usr/local -xf go1.16.linux-amd64.tar.gz
-      export PATH=$PATH:/usr/local/go/bin
-      apt-get update
-      apt-get -y install build-essential    
-      export PIPELINE_USERNAME=$(get_env ibmcloud-api-user)
-      export PIPELINE_PASSWORD=$(get_env ibmcloud-api-key-staging)  
-      export DOCKER_USERNAME=$(get_env docker-username)
-      export DOCKER_PASSWORD=$(get_env docker-password)    
-      export CLUSTER_URL=$(get_env test-cluster-url)
-      export CLUSTER_TOKEN=$(get_env test-cluster-token) 
-      export TRAVIS_BUILD_NUMBER=$BUILD_NUMBER   
-      make setup
-      make test-pipeline-e2e
+    SKIP_ACCEPTANCE_TEST=$(get_env SKIP_ACCEPTANCE_TEST)
+    SKIP_ACCEPTANCE_TEST="$(echo "$SKIP_ACCEPTANCE_TEST" | tr '[:upper:]' '[:lower:]')"
+    if [[ ! -z "$SKIP_ACCEPTANCE_TEST" && "$SKIP_ACCEPTANCE_TEST" != "false" && "$SKIP_ACCEPTANCE_TEST" != "no"  ]]; then
+      echo "Skipping acceptance-test, SKIP_ACCEPTANCE_TEST=$SKIP_ACCEPTANCE_TEST"
+      exit 0
+    fi
+
+    rm -rf .git
+    git clone https://$(get_env git-token)@github.ibm.com/elastic-build-cloud/ebc-gateway-http.git
+    cd ebc-gateway-http
+
+    export intranetId_USR=$(get_env ebc_id)
+    export intranetId_PSW=$(get_env ebc_pw)
+
+    wlo_demand_id=$(get_env WLO_DEMAND_ID)
+    export demandId=$wlo_demand_id
+
+    #(prod or dev to use dev ebc)
+    export ebcEnvironment=dev
+    
+    echo "calling ebc_waitForDemand.sh"
+    json=$(./ebc_waitForDemand.sh)
+    rc=$?
+    echo "return from ebc_waitForDemand.sh"
+    
+    
+    status=$(jq -c '.status' <<< $json)
+    ip=$(jq -c '.machineAddresses.ocpinf' <<< $json)
+    ip=$(echo "$ip" | tr -d '"')
+    
+    PRIVATE_KEY="$(get_env private_key "")"
+    echo -n "${PRIVATE_KEY}" | base64 -d > id_rsa
+    
+    chmod 600 id_rsa
+    pwd
+    ls -l id_rsa
+    
+    echo "oc version:"
+    oc version
+    
+    token=$(ssh -o StrictHostKeyChecking=no -i id_rsa root@$ip "cat ~/auth/kubeadmin-password")
+    
+    echo "demand_id=$wlo_demand_id"
+    echo "*** results from EBC wait:"
+    echo "ip=$ip"
+    echo "status=$status"
+    echo "json=$json"
+    echo "token=$token"
+    
+    if [[ "$rc" == 0 ]]; then
+       echo "EBC create of id: $wlo_demand_id cluster successful"
     else
-      echo "skipping Acceptance test"
+      echo "debug of cluster may be required, issue @ebc debug $wlo_demand_id in #was-ebc channel to keep cluster for debug"
+      echo "issue @ebc debugcomplete $wlo_demand_id when done debugging in #was-ebc channel "
+      exit 1
+    fi
+
+    cd ..
+
+    clusterurl="$ip:6443"
+
+    echo "running cluster.sh"
+    GITHUB_ACCESS_TOKEN=$(get_env git-token)
+    GITHUB_SCRIPT_URL="https://api.github.ibm.com/repos/websphere/operators/contents/scripts/configure-cluster/configure-cluster.sh"
+    curl -H "Authorization: token $GITHUB_ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" "$GITHUB_SCRIPT_URL" | jq -r ".content" | base64 --decode > configure-cluster.sh
+    chmod +x configure-cluster.sh
+    ls -l cluster.sh
+    echo "**** issuing oc login"
+    oc login --insecure-skip-tls-verify $clusterurl -u kubeadmin -p $token
+    echo "Open Shift Console:"
+    console=$(oc whoami --show-console)
+    echo $console
+    echo "*** after issuing oc login"
+    ./configure-cluster.sh -k $(get_env ibmcloud-api-key-staging) -A
+    
+    # Download and configure golang
+    GO_VERSION=$(get_env go-version)
+    if [[ -z "${GO_VERSION}" ]]; then
+      GO_VERSION="$(grep '^go [0-9]\+.[0-9]\+' go.mod | cut -d ' ' -f 2)"
+    fi
+    export GO_VERSION
+
+    # OCP test
+    export PIPELINE_USERNAME=$(get_env ibmcloud-api-user)
+    export PIPELINE_PASSWORD=$(get_env ibmcloud-api-key-staging)
+    export PIPELINE_REGISTRY=$(get_env pipeline-registry)
+    export PIPELINE_OPERATOR_IMAGE=$(get_env pipeline-operator-image)
+    export DOCKER_USERNAME=$(get_env docker-username)
+    export DOCKER_PASSWORD=$(get_env docker-password)
+    #export CLUSTER_URL=$(get_env test-cluster-url)
+    export CLUSTER_URL=$clusterurl
+    #export CLUSTER_USER=$(get_env test-cluster-user kubeadmin)
+    export CLUSTER_TOKEN=$token
+    export RELEASE_TARGET=$(get_env branch)
+    export DEBUG_FAILURE=$(get_env debug-failure)
+
+    # Kind test
+    export FYRE_USER=$(get_env fyre-user)
+    export FYRE_KEY=$(get_env fyre-key)
+    export FYRE_PASS=$(get_env fyre-pass)
+    export FYRE_PRODUCT_GROUP_ID=$(get_env fyre-product-group-id)
+
+
+
+    make test-pipeline-e2e
+    rc=$?
+
+    cd ebc-gateway-http
+
+    if [[ "$rc" == 0 ]]; then
+      ./ebc_complete.sh
+    else
+      hours=$(get_env ebc_autocomplete_hours "6")
+      echo "Your acceptance test failed, the cluster will be retained for $hours hours.  If you need more time to debug ( 72 hours ):"
+      echo "debug of cluster may be required, issue @ebc debug $wlo_demand_id in #was-ebc channel to keep cluster for debug"
+      echo "issue @ebc debugcomplete $wlo_demand_id when done debugging in #was-ebc channel "
+      echo "access console at: $console"
+      echo "credentials: kubeadmin/$token"
+      slack_users=$(get_env slack_users)
+      echo "slack_users=$slack_users"
+      eval "arr=($slack_users)"
+      for user in "${arr[@]}"; do 
+        echo "user=$user"
+        curl -X POST -H 'Content-type: application/json' --data '{"text":"<'$user'>  accceptance test failure see below "}' $(get_env slack_web_hook_url)
+        echo " "
+      done
+      pipeline_url="https://cloud.ibm.com/devops/pipelines/tekton/${PIPELINE_ID}/runs/${PIPELINE_RUN_ID}"
+      curl -X POST -H 'Content-type: application/json' --data '{"text":"Your acceptance test failed."}' $(get_env slack_web_hook_url) </dev/null
+      curl -X POST -H 'Content-type: application/json' --data '{"text":"Failing pipeline: '$pipeline_url'"}' $(get_env slack_web_hook_url) </dev/null
+      curl -X POST -H 'Content-type: application/json' --data '{"text":"The cluster will be retained for '$hours' hours.  If you need more time to debug ( 72 hours ):"}' $(get_env slack_web_hook_url) </dev/null
+      curl -X POST -H 'Content-type: application/json' --data '{"text":"issue @ebc debug '$wlo_demand_id' in #was-ebc channel to keep cluster for debug"}' $(get_env slack_web_hook_url) </dev/null
+      curl -X POST -H 'Content-type: application/json' --data '{"text":"access console at: '$console'"}' $(get_env slack_web_hook_url) </dev/null
+      curl -X POST -H 'Content-type: application/json' --data '{"text":"credentials: kubeadmin/'$token'"}' $(get_env slack_web_hook_url) </dev/null
     fi
 
 scan-artifact:
